version: "3"

services:

  cln-task-manager:
    image: cln-task-manager:1.0
    container_name: cln-task-manager
    ports:
      - 80:80
    environment:
      CLN_TM_DATASOURCE_URL: jdbc:postgresql://cln-task-manager-db:5432/cln-task-manager-db
      CLN_TM_DATASOURCE_USER: cln-task-manager
      CLN_TM_DATASOURCE_PASSWORD: cln-task-manager
      CLN_TM_DATASOURCE_DRIVER: org.postgresql.Driver
      CLN_TM_CONNECTIONPOOL_SIZE_MIN: 2
      CLN_TM_CONNECTIONPOOL_SIZE_MAX: 6
      CLN_TM_CONNECTIONPOOL_IDLE_TIMEOUT: 30000
      CLN_TM_CONNECTIONPOOL_MAX_LIFE_TIME: 2000000
      CLN_TM_CONNECTION_TIMEOUT: 30000
      CLN_TM_THREAD_POOL_CORE_SIZE: 8
      CLN_TM_THREAD_POOL_MAX_SIZE: 128
      CLN_TM_SERVER_PORT: 80
      CLN_TM_H2_ENABLED: "false"
      CLN_TM_CORS_ALLOWED_ORIGIN: "*"
      CLN_TM_AUTH_HEADER_DISABLED: "true"
      CLN_TM_COUNTER_TASK_TIMEOUT_MS: 1000
      CLN_TM_COUNTER_TASK_EMITTER_DURATION_MS: 60000
      CLN_TM_COUNTER_TASK_EMITTER_STEP_MS: 1000
      CLN_TM_COUNTER_TASK_CLEANUP_ENABLED: "true"
      CLN_TM_COUNTER_TASK_CLEANUP_SCHEDULE: 0 0 02 * * *
      CLN_TM_COUNTER_TASK_CLEANUP_CREATED_DAYS: 10

  cln-task-manager-db:
    container_name: cln-task-manager-db
    image: postgres:14rc1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cln-task-manager-db
      POSTGRES_USER: cln-task-manager
      POSTGRES_PASSWORD: cln-task-manager
      PGDATA: /data/postgres
