spring:
  application:
    name: cln-task-manager
  datasource:
    url: jdbc:h2:file:./data/db/clntaskmanager;MODE=PostgreSQL
    username: sa
    password:
    type:
    driver-class-name: org.h2.Driver
    liquibase:
      change-log: classpath:db/changelog-master.yaml

    hikari:
      minimumIdle: 2
      maximumPoolSize: 6
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  liquibase:
    change-log: classpath:db/changelog-master.yaml

server:
  port: 80
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

clnTaskManager:
  cors.allowedOrigin: "*"

#check what hibernate does with every query you introduce.
#logging.level.org.hibernate: TRACE
#logging.level.org.springframework: TRACE
