spring:
  application:
    name: cln-task-manager
  datasource:
    url: ${CLN_TM_DATASOURCE_URL:jdbc:h2:file:./data/db/clntaskmanager;MODE=PostgreSQL}
    username: ${CLN_TM_DATASOURCE_USER:sa}
    password: ${CLN_TM_DATASOURCE_PASSWORD:}
    type:
    driver-class-name: ${CLN_TM_DATASOURCE_DRIVER:org.h2.Driver}
    hikari:
      minimumIdle: ${CLN_TM_CONNECTIONPOOL_SIZE_MIN:2}
      maximumPoolSize: ${CLN_TM_CONNECTIONPOOL_SIZE_MAX:6}
      idleTimeout: ${CLN_TM_CONNECTIONPOOL_IDLE_TIMEOUT:30000}
      maxLifetime: ${CLN_TM_CONNECTIONPOOL_MAX_LIFE_TIME:2000000}
      connectionTimeout: ${CLN_TM_CONNECTION_TIMEOUT:30000}
  task:
    execution:
      pool:
        coreSize: ${CLN_TM_THREAD_POOL_CORE_SIZE:16}
        maxSize: ${CLN_TM_THREAD_POOL_MAX_SIZE:128}

  liquibase:
    change-log: classpath:db/changelog-master.yaml

server:
  port: ${CLN_TM_SERVER_PORT:80}
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" #cluster health probe and discovery.
clnTaskManager:
  h2Enabled: ${CLN_TM_H2_ENABLED:true}
  cors.allowedOrigin: ${CLN_TM_CORS_ALLOWED_ORIGIN:*}
  authheader.disabled: ${CLN_TM_AUTH_HEADER_DISABLED:true}
  counterTask:
    timeoutMs: ${CLN_TM_COUNTER_TASK_TIMEOUT_MS:1000}
    emitterDurationMs: ${CLN_TM_COUNTER_TASK_EMITTER_DURATION_MS:60000}
    emitterStepMs: ${CLN_TM_COUNTER_TASK_EMITTER_STEP_MS:1000}
  taskCleanup:
    enabled: ${CLN_TM_COUNTER_TASK_CLEANUP_ENABLED:true}
    schedule: ${CLN_TM_COUNTER_TASK_CLEANUP_SCHEDULE:0 0 02 * * *} #every day at 2am
    createdDaysAgo: ${CLN_TM_COUNTER_TASK_CLEANUP_CREATED_DAYS:10}

#http://localhost/swagger-ui.html it will not work if clnTaskManager.authheader.enabled true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

#check what hibernate does with every query you introduce.
#logging.level.org.hibernate: TRACE
#logging.level.org.springframework: TRACE
