spring:
  application:
    name: cln-task-manager
  datasource:
    url: ${CLN_TM_DATASOURCE_URL:jdbc:h2:file:./data/db/clntaskmanager;MODE=PostgreSQL}
    username: ${CLN_TM_DATASOURCE_USER:sa}
    password: ${CLN_TM_DATASOURCE_PASSWORD:}
    type:
    driver-class-name: ${CLN_TM_DATASOURCE_DRIVER:org.h2.Driver}
    hikari:
      minimumIdle: ${CLN_TM_CONNECTIONPOOL_SIZE_MIN:2}
      maximumPoolSize: ${CLN_TM_CONNECTIONPOOL_SIZE_MAX:6}
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: ${CLN_TM_CONNECTION_TIMEOUT:30000}

  liquibase:
    change-log: classpath:db/changelog-master.yaml

server:
  port: ${CLN_TM_SERVER_PORT:80}
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

clnTaskManager:
  h2Enabled: ${CLN_TM_H2_ENABLED:true}
  cors.allowedOrigin: ${CLN_TM_CORS_ALLOWED_ORIGIN:"*"}
  authheader.enabled: ${CLN_TM_AUTH_HEADER_ENABLED:false}

#http://localhost/swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

#check what hibernate does with every query you introduce.
#logging.level.org.hibernate: TRACE
#logging.level.org.springframework: TRACE
